--- #YAML:1.0
name:               Tie-Array-AsHash
version:            0.011
abstract:           Like Tie::File::AsHash (now: groundwork for it) but
author:
    - Chris Angell <chris@chrisangell.com>, Jens Rehsack <rehsack@web.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Params::Util:  0.35
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
